name: "Build and release Neovim image"

inputs:
  password:
    description: "Docker Hub password"
    required: true
  target:
    description: "The target version of Neovim"
    required: true
  tag:
    description: "Final image's tag (default to 'target')"
    required: false
  allowOverride:
    description: "If true, the action will override the existing image on the registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps: 
    - run: |
        export PASSWORD=${{ inputs.password }}
        export TARGET=${{ inputs.target }}
        export TAG=${{ inputs.tag }}
        export ALLOW_OVERRIDE=${{ inputs.allowOverride }}

        ./.github/actions/release/run.sh
      shell: bash
