name: "Build and release Neovim image"

inputs:
  password:
    description: "Docker Hub password"
    required: true
  version:
    description: "The version of Neovim"
    required: true
  tag:
    description: "Final image's tag (default to 'version')"
    required: false
  allowOverride:
    description: "If true, the action will override the existing image on the registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps: 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Build and push images
      shell: bash
      run: |
        export PASSWORD=${{ inputs.password }}
        export VERSION=${{ inputs.version }}
        export TAG=${{ inputs.tag }}
        export ALLOW_OVERRIDE=${{ inputs.allowOverride }}

        ./.github/actions/release/run.sh
