name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - ".docker/**"
  schedule:
    - cron: "25 5 * * *"

jobs:
  latest-alpine:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: stable
      image_version: latest,latest-alpine,{version_major}-alpine,{version_major}.{version_minor}-alpine,{version_major}.{version_minor}.{version_patch}-alpine
      distro_name: alpine
      distro_version: latest

  latest-bookworm:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: stable
      image_version: latest-bookworm,{version_major}-bookworm,{version_major}.{version_minor}-bookworm,{version_major}.{version_minor}.{version_patch}-bookworm
      distro_name: debian
      distro_version: bookworm

  latest-bullseye:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: stable
      image_version: latest-bullseye,{version_major}-bullseye,{version_major}.{version_minor}-bullseye,{version_major}.{version_minor}.{version_patch}-bullseye
      distro_name: debian
      distro_version: bullseye

  nightly-alpine:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: nightly
      image_version: nightly-alpine
      distro_name: alpine
      distro_version: latest

  nightly-bookworm:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: nightly
      image_version: nightly-bookworm
      distro_name: debian
      distro_version: bookworm

  nightly-bullseye:
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
    with:
      neovim_version: nightly
      image_version: nightly-bullseye
      distro_name: debian
      distro_version: bullseye
